package errorpkg

const (
	ERROR_CODE_FROM_GO           = 1
	ERROR_CODE_FROM_DATABASE     = 2
	ERROR_CODE_BAD_REQUEST       = 3
	ERROR_CODE_INTERNAL_SERVER   = 4
	ERROR_CODE_NOT_FOUND         = 5
	ERROR_CODE_PERMISSION_DENIED = 6
	ERROR_CODE_FORBIDDEN         = 7
)
